config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  root 'users#index'
  resources :users
  get 'update_users', to: 'users#update_users'
  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true

  def github_user?
    uri = URI("https://github.com/#{self.username}/")
    response = Net::HTTP.get_response(uri)
    response.code == '404' ? false : true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController <ApplicationController
  include LeaderboardMethod

  def index
    @users = User.all.order(rank: :asc).paginate(page: params[:page], per_page: 10)
    @users.each do |user|
      get_rank(user)
    end
  end

  def create
    @user = User.new(user_params)

    if @user.github_user?
      if @user.save
        TotalCommitsWorker.perform_async(@user.id)
        flash[:success] = I18n.t 'user.success.created'
      elsif leaderboard.check_member?(@user.username)
        flash[:danger] = I18n.t 'user.error.already_present'
      else
        flash[:danger] = I18n.t 'user.error.not_created'
      end
      redirect_to root_path
    else
      flash[:danger] = I18n.t 'user.error.invalid_github_username'
      redirect_to root_path
    end
  end

  def edit
    @user = User.where(id: params[:id]).first
  end

  def update
    @user = User.where(id: params[:id]).first
    username = params[:user][:username]
    uri = URI("https://github.com/#{username}/")
    response = Net::HTTP.get_response(uri)
    if response.code == '404'
      flash[:danger] = I18n.t 'user.error.not_updated'
    else
      @user.update_attributes(user_params)
      flash[:success] = I18n.t 'user.success.updated'
    end
    redirect_to root_path
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy and leaderboard.remove_member(@user.username)
      flash[:success] = I18n.t 'user.success.deleted', name: @user.name, username: @user.username
      redirect_to root_path
    end
  end

  def update_users
    @users = User.all
    @users.each do |user|
      TotalCommitsWorker.perform_async(user.id)
    end
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :username)
    end

    def get_rank(user)
      leaderboard.rank_member(user.username, user.total_commits)
      user.rank = leaderboard.rank_for(user.username)
      user.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'LeaderboardApp'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> fade-in">
        <button class="close" data-dismiss="alert">×</button> 
        <%= value %> 
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title" id="myModalLabel"> Edit User Information </h4>
    </div>
    <div class="modal-body">
      <%= form_for(@user, html: {method: 'put'}) do |f| %>
        <%= f.label :name, 'New Name' %>
        <%= f.text_field :name, required: true, class: 'form-control' %>

        <%= f.label :username, 'New GitHub Username' %>
        <%= f.text_field :username, required: true, class: 'form-control' %>

        <%= f.submit 'Update Details', class: 'button' %>
      <% end %> 
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<% provide(:title, "Github Users") %>

<div class='left-section'>
  <%= form_for(User.new, remote: true, html: { method: 'post' }, id: 'submit')  do |f| %>
    <%= render partial: 'users/new', locals: { f: f } %>
  <% end %>
</div>

<h3 class='margin-10'> Leaderboard as per Github Contributions </h3>

<div class='update-button-position'>
  <%= button_to 'Update Leaderboard', update_users_path, class: 'button', method: :get %>
</div>

<div>
  <table class='leaderboard-table'>
    <thead>
      <tr>
        <th> Rank </th>
        <th> Name </th>
        <th> Github Username </th>
        <th> Today's Commits </th>
        <th> Commits Since <%= Time.now.day %>/<%= Time.now.month %>/<%= Time.now.year - 1 %> </th>
        <th> Remove from Leaderboard </th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td> <%= user.rank %> </td>
          <td> <%= link_to(user.name, edit_user_path(user), remote: true, data: { toggle: "modal", target: "#myModal" }, title: 'Edit Information', rel: 'tooltip') %> </td>
          <td> <%= link_to user.username, "https://github.com/#{user.username}", title: 'Go to Github Page', rel: 'tooltip' %> </td>
          <td> <%= user.commits_made_today %> Commits </td>
          <td> <%= user.total_commits %> Commits </td>
          <td> 
            <%= button_to user, method: :delete, remote: true, class: 'btn btn-danger delete-user', data: { confirm: 'Are you sure to remove?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @users %>
</div>

<div class='update-button-position'>
  <%= button_to 'Update Leaderboard', update_users_path, class: 'button', method: :get %>
</div>

app/views/users/_new.html.erb
<div class='col-sm-5 form-inline'>
  <%= f.label :name, 'Your Name' %>
  <%= f.text_field :name, placeholder: 'Enter Name', required: true, class: 'form-control' %>
</div>
<div class='col-sm-5 form-inline'>
  <%= f.label :username, 'GitHub Username' %>
  <%= f.text_field :username, placeholder: 'GitHub Username', required: true, class: 'form-control' %>
</div>
<div class='col-md-4 button-position'>
  <%= f.submit 'Add to Leaderboard', class: 'button' %>
</div>

app/views/users/create.js.erb
$('#submit').on('ajax:success', function() {
  show('<%= j render partial: 'index' %>');
});

app/views/users/destroy.js.erb
$('.delete-user').on('ajax:success', function() {
  show('<%= j render partial: 'index' %>');
});

app/views/users/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_for(@user, html: {method: 'put'}) do |f| %>

    <div class='col-md-11'>
      <%= f.label :name, 'New Name' %>
      <%= f.text_field :name, required: true, class: 'form-control' %>
    </div>

    <div class='col-md-11'>
      <%= f.label :username, 'New GitHub Username' %>
      <%= f.text_field :username, required: true, class: 'form-control' %>
    </div>

    <div class='col-md-11'>
      <%= f.submit 'Update Details', class: 'button' %>
    </div>

  <% end %> 
</div>

app/views/users/edit.js.erb
$("#myModal").html("<%= escape_javascript(render 'edit') %>")
$("#myModal").modal("show")

app/views/users/index.html.erb
<% provide(:title, "Github Users") %>

<div class='left-section'>
  <%= form_for(User.new, remote: true, html: { method: 'post' }, id: 'submit')  do |f| %>
    <%= render partial: 'users/new', locals: { f: f } %>
  <% end %>
</div>

<h3 class='margin-10'> Leaderboard as per Github Contributions </h3>

<div class='update-button-position'>
  <%= button_to 'Update Leaderboard', update_users_path, class: 'button', method: :get %>
</div>

<div>
  <table class='leaderboard-table'>
    <thead>
      <tr>
        <th> Rank </th>
        <th> Name </th>
        <th> Github Username </th>
        <th> Today's Commits </th>
        <th> Commits Since <%= Time.now.day %>/<%= Time.now.month %>/<%= Time.now.year - 1 %> </th>
        <th> Remove from Leaderboard </th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td> <%= user.rank %> </td>
          <td> <%= link_to(user.name, edit_user_path(user), remote: true, data: { toggle: "modal", target: "#myModal" }, title: 'Edit Information', rel: 'tooltip') %> </td>
          <td> <%= link_to user.username, "https://github.com/#{user.username}", title: 'Go to Github Page', rel: 'tooltip' %> </td>
          <td> <%= user.commits_made_today %> Commits </td>
          <td> <%= user.total_commits %> Commits </td>
          <td> 
            <%= button_to user, method: :delete, remote: true, class: 'btn btn-danger delete-user', data: { confirm: 'Are you sure to remove?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @users %>
</div>

<div class="modal fade" id="myModal" role="dialog" aria-hidden="true">
</div>